# Statystyczne Reguły Decyzjne - wstęp do algebry liniowej w Pythonie

Do algebry liniowej w Pythonie jednym z najpopularniejszych pakietów jest pakiet Numpy (https://numpy.org/)

In [2]:
!pip install numpy

plotnine 0.5.1 has requirement matplotlib>=3.0.0, but you'll have matplotlib 2.1.0 which is incompatible.
plotnine 0.5.1 has requirement scipy>=1.0.0, but you'll have scipy 0.19.1 which is incompatible.
neptune-cli 2.8.5 has requirement Flask==0.12.0, but you'll have flask 0.12.4 which is incompatible.
docker-py 1.10.3 has requirement requests<2.11,>=2.5.2, but you'll have requests 2.21.0 which is incompatible.
apache-beam 2.2.0 has requirement httplib2<0.10,>=0.8, but you'll have httplib2 0.12.0 which is incompatible.
apache-beam 2.2.0 has requirement protobuf<=3.3.0,>=3.2.0, but you'll have protobuf 3.7.0 which is incompatible.
apache-beam 2.2.0 has requirement six<1.11,>=1.9, but you'll have six 1.11.0 which is incompatible.
You are using pip version 10.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [3]:
import numpy as np

## 1. Wektor 

In [4]:
v = np.array(
    [
        [1], 
        [2], 
        [3]
    ]
)
v

array([[1],
       [2],
       [3]])

In [5]:
print(v.shape)

(3, 1)


In [6]:
v_single_dim = np.array([1, 2, 3])
print(v_single_dim.shape)

(3,)


## 2. Macierz

In [7]:
M = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print(M.shape)

(3, 3)


In [9]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [10]:
print(np.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [11]:
print(np.full((2,2), 10))

[[10 10]
 [10 10]]


In [12]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])
M = np.vstack([v1, v2, v3])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
v1 = np.array([1, 4, 7])
v2 = np.array([2, 5, 8])
v3 = np.array([3, 6, 9])
M = np.hstack([v1, v2, v3])
M

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [15]:
v1 = np.array([[1], [4], [7]])
v2 = np.array([[2], [5], [8]])
v3 = np.array([[3], [6], [9]])
M = np.hstack([v1, v2, v3])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 2.1 Indeksowanie macierzy/wektorów

In [16]:
M[1, 2]

6

In [17]:
M[:2, 1:3]

array([[2, 3],
       [5, 6]])

## 3. Podstawowe działania

### 3.1. Dodawanie wektorów

In [18]:
print(v + v)

[[2]
 [4]
 [6]]


### 3.2. Mnożenie wektora przez skalar

In [19]:
print(3*v)

[[3]
 [6]
 [9]]


### 3.3. Mnożenie macierzy

In [20]:
print(M.dot(v))

[[14]
 [32]
 [50]]


### 3.4. Iloczyn skalarny

In [21]:
print(v.dot(v))

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [22]:
print(v.T.dot(v))

[[14]]


### 3.5. Iloczyn wektorowy

In [23]:
v1 = np.array([[1], [2], [3]])
v2 = np.array([[4], [5], [6]])
print(np.cross(v1, v2, axisa=0, axisb=0).T)

[[-3]
 [ 6]
 [-3]]


### 3.6. Mnożenie element x element

In [24]:
print(np.multiply(M, v))

[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


In [25]:
print(np.multiply(v, v))

[[1]
 [4]
 [9]]


### 3.7. Transpozycja

In [26]:
print(M.T)
print(v.T.shape)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
(1, 3)


In [27]:
print(v.T)
print(v.T.shape)

[[1 2 3]]
(1, 3)


### 3.8. Odwracanie macierzy

In [28]:
print(M)
print(np.linalg.inv(M))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


LinAlgError: Singular matrix

In [29]:
M = np.array(
    [
        [2, 2, 3],
        [2, 5, 1],
        [2, 1, 9]
    ]
)
print(np.linalg.inv(M))

[[ 1.375   -0.46875 -0.40625]
 [-0.5      0.375    0.125  ]
 [-0.25     0.0625   0.1875 ]]


### 3.9. Wyznacznik macierzy

In [30]:
print(np.linalg.det(M))

32.0


### 3.10. Wartości i wektory własne macierzy

In [31]:
eigvals, eigvecs = np.linalg.eig(M)
print(eigvals)
print()
print(eigvecs)

[ 0.60785954 10.26234309  5.12979736]

[[ 0.91068364 -0.39015588 -0.23661116]
 [-0.37546028 -0.3128424  -0.90408432]
 [-0.17229299 -0.8659723   0.35587455]]


### 3.11. Rozkład według wartości osobliwych (SVD - Singular Value Decomposition)

In [32]:
U, S, Vtranspose = np.linalg.svd(M)
print(U)
print()
print(S)
print()
print (Vtranspose)

[[-0.38002929 -0.22696159 -0.89669737]
 [-0.29184144 -0.89049115  0.34907605]
 [-0.87772793  0.39435258  0.27217592]]

[10.30887603  5.13435089  0.60457908]

[[-0.30063387 -0.30042011 -0.90518895]
 [-0.2816715  -0.87879197  0.38520883]
 [-0.91119726  0.37077275  0.17957485]]
